### ISSUE TITLE
Carl build for master14 fails at building Boost step

### ISSUE THREAD

**Issue by oyendrila-dobe** [ths-rwth/carl#42]
I do have the latest boost in my system, but I guess it prompts that the new boost version might have missing dependencies. I have even tried installing by forcing shipped resources, instead of downloading but it always fails with the same message.

<img width="821" alt="Screen Shot 2021-05-11 at 2 12 01 PM" src="https://user-images.githubusercontent.com/14862450/117864503-e268f300-b262-11eb-9aa4-9f353a2b894b.png">

**Comment by modass** [comment]
I can observe the same, the current url for the boost download is not reachable anmore (i.e. https://dl.bintray.com/boostorg/release/ itself cannot be accessed anymore).

Maybe use https://sourceforge.net/projects/boost/files/boost/ + VERSION instead?

**Comment by oyendrila-dobe** [comment]
I did change the link as suggested in the cmake file of carl but it ends up with the same error. Is there any other location where the link must be changed?
