### ISSUE TITLE
Compilation errors when disabling CoCoA

### ISSUE THREAD

**Issue by volkm** [ths-rwth/carl#45]
I tried building the latest master of CArL out of curiosity to see whether it would work with [Storm](https://github.com/moves-rwth/storm). I got some compilation errors though.

CoCoA is required for several parts even though I disabled via `-DUSE_COCOA=OFF`. It seems that `#ifdef USE_COCOA` should be added to more parts. The compilation errors should be reproducible by disabling CoCoA.
The first error for me occurred in:
https://github.com/ths-rwth/carl/blob/master/src/carl/ran/interval/AlgebraicSubstitution.h

BTW: I want to disable CoCoA as building the library also failed for me with gcc-11.

**Comment by derjasper** [comment]
Will be fixed with the next release in June.
