### ISSUE TITLE
CoCoA needs to be updated to 0.99800

### ISSUE THREAD

**Issue by ForceFaction** [ths-rwth/carl#48]
Hi,

CoCoA needs to be updated to 0.99800 because it fixed these issues:
  - Removed template fn apply (clash with std::apply) -- see redmine 1601
  - Replaced calls to apply by direct applic of ringhom (redmine 1467, 1598)

Those fixes are necessary as CoCoA otherwise doesn't build with a new Compiler (GCC11+; i only tested GCC12, but #45 used GCC11).

**Comment by derjasper** [comment]
Will be fixed with the next release in June.
