### ISSUE TITLE
Link for CoCoA lib download needs update

### ISSUE THREAD

**Issue by rpgoldman** [ths-rwth/carl#50]
The new URL is `https://cocoa.dima.unige.it/cocoa/cocoalib/tgz/CoCoALib-${COCOA_VERSION}.tgz` HTTPS instead of HTTP, and the directory structure has changed.

**Comment by derjasper** [comment]
Thanks for letting know. The next release of CArL will contain a fix.

Note that development happens in our internal repository, so the changes will only be visible on GitHub after release.
